version: '3.3'
services:

    app:
        build: app.py
        links:
            - db
        ports:
            - "80:80"
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    # Names our volume
volumes:
    my-db: 

'''Creating network "proy-alembic_default" with the default driver
Creating volume "proy-alembic_my-db" with default driver
Building app
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1078, in up
  File "compose/cli/main.py", line 1074, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 367, in ensure_image_exists
  File "compose/service.py", line 1106, in build
  File "site-packages/docker/api/build.py", line 148, in build
TypeError: You must specify a directory to build in path
[64424] Failed to execute script docker-compose''''